### ISSUE TITLE
function request: expose GetJson(str string) result to command line argument

### ISSUE THREAD

**Issue by hihihippp** [Asutorufa/hujiang_dictionary#7]
I want to use this perfect dictionary tool in command line pipe, for example
fzf --preview  to show the dictionary search result and using mpv to play the mp3 link at same time.  there are many other cases for the need of the meta data of the search result. 

As json is standard and popular format, this fuction will expose the power of this dictionary to all the command line world too. it's cool!

**Comment by Asutorufa** [comment]
add json flag output json, eg:

```shell
hj -json -jp こにちは
```
